Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:region:account_id:task-definition/task_defn:revision"
        LoadBalancerInfo:
          ContainerName: "container_name"
          ContainerPort: 3001
# arn:aws:ecs:ap-southeast-2:368355641188:task-definition/ram-task-fg:4